language: node_js

node_js:
  - "4.8.0"
  - "6.10.0"
  - "7.6.0"

before_install:
  - npm install --production
  - npm install mocha

env:
 - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libprotobuf-dev

sudo: false
